name: posyandu_backend
description: A server app using the shelf package and Docker.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  uuid: ^3.0.6
  cron: ^0.5.0
  dart_jsonwebtoken: ^2.4.1
  intl: ^0.17.0
  mysql_utils: ^2.0.10
  shelf_hotreload: ^1.3.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
